// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alldoudizhu.proto

package com.yaowan.protobuf.game;

public final class GAllDouDiZhu {
  private GAllDouDiZhu() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GMsg_12040004OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
    boolean hasAction();
    com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction();
    
    // required int32 current_seat = 2;
    boolean hasCurrentSeat();
    int getCurrentSeat();
    
    // required int32 wait_time = 3;
    boolean hasWaitTime();
    int getWaitTime();
  }
  public static final class GMsg_12040004 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12040004OrBuilder {
    // Use GMsg_12040004.newBuilder() to construct.
    private GMsg_12040004(Builder builder) {
      super(builder);
    }
    private GMsg_12040004(boolean noInit) {}
    
    private static final GMsg_12040004 defaultInstance;
    public static GMsg_12040004 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12040004 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction() {
      return action_;
    }
    
    // required int32 current_seat = 2;
    public static final int CURRENT_SEAT_FIELD_NUMBER = 2;
    private int currentSeat_;
    public boolean hasCurrentSeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurrentSeat() {
      return currentSeat_;
    }
    
    // required int32 wait_time = 3;
    public static final int WAIT_TIME_FIELD_NUMBER = 3;
    private int waitTime_;
    public boolean hasWaitTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWaitTime() {
      return waitTime_;
    }
    
    private void initFields() {
      action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
      currentSeat_ = 0;
      waitTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentSeat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWaitTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currentSeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, waitTime_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentSeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, waitTime_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentSeat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        waitTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currentSeat_ = currentSeat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.waitTime_ = waitTime_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040004.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasCurrentSeat()) {
          setCurrentSeat(other.getCurrentSeat());
        }
        if (other.hasWaitTime()) {
          setWaitTime(other.getWaitTime());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        if (!hasCurrentSeat()) {
          
          return false;
        }
        if (!hasWaitTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction value = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentSeat_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              waitTime_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
      private com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction() {
        return action_;
      }
      public Builder setAction(com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
        
        return this;
      }
      
      // required int32 current_seat = 2;
      private int currentSeat_ ;
      public boolean hasCurrentSeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurrentSeat() {
        return currentSeat_;
      }
      public Builder setCurrentSeat(int value) {
        bitField0_ |= 0x00000002;
        currentSeat_ = value;
        
        return this;
      }
      public Builder clearCurrentSeat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentSeat_ = 0;
        
        return this;
      }
      
      // required int32 wait_time = 3;
      private int waitTime_ ;
      public boolean hasWaitTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWaitTime() {
        return waitTime_;
      }
      public Builder setWaitTime(int value) {
        bitField0_ |= 0x00000004;
        waitTime_ = value;
        
        return this;
      }
      public Builder clearWaitTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        waitTime_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12040004)
    }
    
    static {
      defaultInstance = new GMsg_12040004(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12040004)
  }
  
  public interface GMsg_12040006OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
    boolean hasAction();
    com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction();
    
    // required .com.yaowan.protobuf.game.GDouDiZhuTable table = 2;
    boolean hasTable();
    com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable getTable();
  }
  public static final class GMsg_12040006 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12040006OrBuilder {
    // Use GMsg_12040006.newBuilder() to construct.
    private GMsg_12040006(Builder builder) {
      super(builder);
    }
    private GMsg_12040006(boolean noInit) {}
    
    private static final GMsg_12040006 defaultInstance;
    public static GMsg_12040006 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12040006 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction() {
      return action_;
    }
    
    // required .com.yaowan.protobuf.game.GDouDiZhuTable table = 2;
    public static final int TABLE_FIELD_NUMBER = 2;
    private com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable table_;
    public boolean hasTable() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable getTable() {
      return table_;
    }
    
    private void initFields() {
      action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
      table_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTable().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, table_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, table_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
        bitField0_ = (bitField0_ & ~0x00000001);
        table_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.table_ = table_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040006.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasTable()) {
          mergeTable(other.getTable());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        if (!hasTable()) {
          
          return false;
        }
        if (!getTable().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction value = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 18: {
              com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.Builder subBuilder = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.newBuilder();
              if (hasTable()) {
                subBuilder.mergeFrom(getTable());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTable(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.yaowan.protobuf.game.DouDiZhuAction action = 1;
      private com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction getAction() {
        return action_;
      }
      public Builder setAction(com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.yaowan.protobuf.game.GDouDiZhu.DouDiZhuAction.GA_DARK_GRAB;
        
        return this;
      }
      
      // required .com.yaowan.protobuf.game.GDouDiZhuTable table = 2;
      private com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable table_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.getDefaultInstance();
      public boolean hasTable() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable getTable() {
        return table_;
      }
      public Builder setTable(com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable value) {
        if (value == null) {
          throw new NullPointerException();
        }
        table_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setTable(
          com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.Builder builderForValue) {
        table_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeTable(com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            table_ != com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.getDefaultInstance()) {
          table_ =
            com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.newBuilder(table_).mergeFrom(value).buildPartial();
        } else {
          table_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearTable() {
        table_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuTable.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12040006)
    }
    
    static {
      defaultInstance = new GMsg_12040006(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12040006)
  }
  
  public interface GMsg_12040007OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.yaowan.protobuf.game.GDouDiZhuPai pai = 1;
    boolean hasPai();
    com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai getPai();
  }
  public static final class GMsg_12040007 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12040007OrBuilder {
    // Use GMsg_12040007.newBuilder() to construct.
    private GMsg_12040007(Builder builder) {
      super(builder);
    }
    private GMsg_12040007(boolean noInit) {}
    
    private static final GMsg_12040007 defaultInstance;
    public static GMsg_12040007 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12040007 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .com.yaowan.protobuf.game.GDouDiZhuPai pai = 1;
    public static final int PAI_FIELD_NUMBER = 1;
    private com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai pai_;
    public boolean hasPai() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai getPai() {
      return pai_;
    }
    
    private void initFields() {
      pai_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPai()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, pai_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pai_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pai_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pai_ = pai_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040007.getDefaultInstance()) return this;
        if (other.hasPai()) {
          mergePai(other.getPai());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPai()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.Builder subBuilder = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.newBuilder();
              if (hasPai()) {
                subBuilder.mergeFrom(getPai());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPai(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.yaowan.protobuf.game.GDouDiZhuPai pai = 1;
      private com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai pai_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.getDefaultInstance();
      public boolean hasPai() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai getPai() {
        return pai_;
      }
      public Builder setPai(com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai value) {
        if (value == null) {
          throw new NullPointerException();
        }
        pai_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setPai(
          com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.Builder builderForValue) {
        pai_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergePai(com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            pai_ != com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.getDefaultInstance()) {
          pai_ =
            com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.newBuilder(pai_).mergeFrom(value).buildPartial();
        } else {
          pai_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearPai() {
        pai_ = com.yaowan.protobuf.game.GDouDiZhu.GDouDiZhuPai.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12040007)
    }
    
    static {
      defaultInstance = new GMsg_12040007(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12040007)
  }
  
  public interface GMsg_11040010OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 is_auto = 1;
    boolean hasIsAuto();
    int getIsAuto();
  }
  public static final class GMsg_11040010 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_11040010OrBuilder {
    // Use GMsg_11040010.newBuilder() to construct.
    private GMsg_11040010(Builder builder) {
      super(builder);
    }
    private GMsg_11040010(boolean noInit) {}
    
    private static final GMsg_11040010 defaultInstance;
    public static GMsg_11040010 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_11040010 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 is_auto = 1;
    public static final int IS_AUTO_FIELD_NUMBER = 1;
    private int isAuto_;
    public boolean hasIsAuto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getIsAuto() {
      return isAuto_;
    }
    
    private void initFields() {
      isAuto_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, isAuto_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, isAuto_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        isAuto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isAuto_ = isAuto_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_11040010.getDefaultInstance()) return this;
        if (other.hasIsAuto()) {
          setIsAuto(other.getIsAuto());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isAuto_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 is_auto = 1;
      private int isAuto_ ;
      public boolean hasIsAuto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIsAuto() {
        return isAuto_;
      }
      public Builder setIsAuto(int value) {
        bitField0_ |= 0x00000001;
        isAuto_ = value;
        
        return this;
      }
      public Builder clearIsAuto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isAuto_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_11040010)
    }
    
    static {
      defaultInstance = new GMsg_11040010(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_11040010)
  }
  
  public interface GMsg_12040010OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 is_auto = 1;
    boolean hasIsAuto();
    int getIsAuto();
  }
  public static final class GMsg_12040010 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12040010OrBuilder {
    // Use GMsg_12040010.newBuilder() to construct.
    private GMsg_12040010(Builder builder) {
      super(builder);
    }
    private GMsg_12040010(boolean noInit) {}
    
    private static final GMsg_12040010 defaultInstance;
    public static GMsg_12040010 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12040010 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 is_auto = 1;
    public static final int IS_AUTO_FIELD_NUMBER = 1;
    private int isAuto_;
    public boolean hasIsAuto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getIsAuto() {
      return isAuto_;
    }
    
    private void initFields() {
      isAuto_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, isAuto_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, isAuto_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        isAuto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isAuto_ = isAuto_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040010.getDefaultInstance()) return this;
        if (other.hasIsAuto()) {
          setIsAuto(other.getIsAuto());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isAuto_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 is_auto = 1;
      private int isAuto_ ;
      public boolean hasIsAuto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIsAuto() {
        return isAuto_;
      }
      public Builder setIsAuto(int value) {
        bitField0_ |= 0x00000001;
        isAuto_ = value;
        
        return this;
      }
      public Builder clearIsAuto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isAuto_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12040010)
    }
    
    static {
      defaultInstance = new GMsg_12040010(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12040010)
  }
  
  public interface GMsg_12040011OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int32 action = 1;
    boolean hasAction();
    int getAction();
  }
  public static final class GMsg_12040011 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12040011OrBuilder {
    // Use GMsg_12040011.newBuilder() to construct.
    private GMsg_12040011(Builder builder) {
      super(builder);
    }
    private GMsg_12040011(boolean noInit) {}
    
    private static final GMsg_12040011 defaultInstance;
    public static GMsg_12040011 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12040011 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int32 action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAction() {
      return action_;
    }
    
    private void initFields() {
      action_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, action_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, action_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011, Builder>
        implements com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011OrBuilder {
      // Construct using com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 build() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 buildPartial() {
        com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 result = new com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011 other) {
        if (other == com.yaowan.protobuf.game.GAllDouDiZhu.GMsg_12040011.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              action_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 action = 1;
      private int action_ ;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAction() {
        return action_;
      }
      public Builder setAction(int value) {
        bitField0_ |= 0x00000001;
        action_ = value;
        
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12040011)
    }
    
    static {
      defaultInstance = new GMsg_12040011(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12040011)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
