// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: center.proto

package com.yaowan.protobuf.game;

public final class GCenter {
  private GCenter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CGame_12100001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string address = 1;
    boolean hasAddress();
    String getAddress();
  }
  public static final class CGame_12100001 extends
      com.google.protobuf.GeneratedMessageLite
      implements CGame_12100001OrBuilder {
    // Use CGame_12100001.newBuilder() to construct.
    private CGame_12100001(Builder builder) {
      super(builder);
    }
    private CGame_12100001(boolean noInit) {}
    
    private static final CGame_12100001 defaultInstance;
    public static CGame_12100001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CGame_12100001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAddressBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAddressBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GCenter.CGame_12100001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GCenter.CGame_12100001, Builder>
        implements com.yaowan.protobuf.game.GCenter.CGame_12100001OrBuilder {
      // Construct using com.yaowan.protobuf.game.GCenter.CGame_12100001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GCenter.CGame_12100001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100001 build() {
        com.yaowan.protobuf.game.GCenter.CGame_12100001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GCenter.CGame_12100001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GCenter.CGame_12100001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100001 buildPartial() {
        com.yaowan.protobuf.game.GCenter.CGame_12100001 result = new com.yaowan.protobuf.game.GCenter.CGame_12100001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GCenter.CGame_12100001 other) {
        if (other == com.yaowan.protobuf.game.GCenter.CGame_12100001.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              address_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string address = 1;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = getDefaultInstance().getAddress();
        
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        address_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.CGame_12100001)
    }
    
    static {
      defaultInstance = new CGame_12100001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.CGame_12100001)
  }
  
  public interface CGame_12100002OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string open_id = 1;
    boolean hasOpenId();
    String getOpenId();
    
    // optional int32 time = 2;
    boolean hasTime();
    int getTime();
    
    // optional string sign = 3;
    boolean hasSign();
    String getSign();
    
    // optional string imei = 4;
    boolean hasImei();
    String getImei();
    
    // optional int32 qd = 5;
    boolean hasQd();
    int getQd();
  }
  public static final class CGame_12100002 extends
      com.google.protobuf.GeneratedMessageLite
      implements CGame_12100002OrBuilder {
    // Use CGame_12100002.newBuilder() to construct.
    private CGame_12100002(Builder builder) {
      super(builder);
    }
    private CGame_12100002(boolean noInit) {}
    
    private static final CGame_12100002 defaultInstance;
    public static CGame_12100002 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CGame_12100002 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string open_id = 1;
    public static final int OPEN_ID_FIELD_NUMBER = 1;
    private java.lang.Object openId_;
    public boolean hasOpenId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getOpenId() {
      java.lang.Object ref = openId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          openId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOpenIdBytes() {
      java.lang.Object ref = openId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        openId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTime() {
      return time_;
    }
    
    // optional string sign = 3;
    public static final int SIGN_FIELD_NUMBER = 3;
    private java.lang.Object sign_;
    public boolean hasSign() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sign_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string imei = 4;
    public static final int IMEI_FIELD_NUMBER = 4;
    private java.lang.Object imei_;
    public boolean hasImei() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imei_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 qd = 5;
    public static final int QD_FIELD_NUMBER = 5;
    private int qd_;
    public boolean hasQd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getQd() {
      return qd_;
    }
    
    private void initFields() {
      openId_ = "";
      time_ = 0;
      sign_ = "";
      imei_ = "";
      qd_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOpenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSignBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, qd_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOpenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSignBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImeiBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, qd_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GCenter.CGame_12100002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GCenter.CGame_12100002, Builder>
        implements com.yaowan.protobuf.game.GCenter.CGame_12100002OrBuilder {
      // Construct using com.yaowan.protobuf.game.GCenter.CGame_12100002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        openId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        qd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100002 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GCenter.CGame_12100002.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100002 build() {
        com.yaowan.protobuf.game.GCenter.CGame_12100002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GCenter.CGame_12100002 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GCenter.CGame_12100002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100002 buildPartial() {
        com.yaowan.protobuf.game.GCenter.CGame_12100002 result = new com.yaowan.protobuf.game.GCenter.CGame_12100002(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.openId_ = openId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.qd_ = qd_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GCenter.CGame_12100002 other) {
        if (other == com.yaowan.protobuf.game.GCenter.CGame_12100002.getDefaultInstance()) return this;
        if (other.hasOpenId()) {
          setOpenId(other.getOpenId());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasSign()) {
          setSign(other.getSign());
        }
        if (other.hasImei()) {
          setImei(other.getImei());
        }
        if (other.hasQd()) {
          setQd(other.getQd());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              openId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sign_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imei_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              qd_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string open_id = 1;
      private java.lang.Object openId_ = "";
      public boolean hasOpenId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getOpenId() {
        java.lang.Object ref = openId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          openId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOpenId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        openId_ = value;
        
        return this;
      }
      public Builder clearOpenId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        openId_ = getDefaultInstance().getOpenId();
        
        return this;
      }
      void setOpenId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        openId_ = value;
        
      }
      
      // optional int32 time = 2;
      private int time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTime() {
        return time_;
      }
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        
        return this;
      }
      
      // optional string sign = 3;
      private java.lang.Object sign_ = "";
      public boolean hasSign() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSign(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sign_ = value;
        
        return this;
      }
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sign_ = getDefaultInstance().getSign();
        
        return this;
      }
      void setSign(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        sign_ = value;
        
      }
      
      // optional string imei = 4;
      private java.lang.Object imei_ = "";
      public boolean hasImei() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImei(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imei_ = value;
        
        return this;
      }
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imei_ = getDefaultInstance().getImei();
        
        return this;
      }
      void setImei(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        imei_ = value;
        
      }
      
      // optional int32 qd = 5;
      private int qd_ ;
      public boolean hasQd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getQd() {
        return qd_;
      }
      public Builder setQd(int value) {
        bitField0_ |= 0x00000010;
        qd_ = value;
        
        return this;
      }
      public Builder clearQd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        qd_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.CGame_12100002)
    }
    
    static {
      defaultInstance = new CGame_12100002(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.CGame_12100002)
  }
  
  public interface CGame_12100003OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class CGame_12100003 extends
      com.google.protobuf.GeneratedMessageLite
      implements CGame_12100003OrBuilder {
    // Use CGame_12100003.newBuilder() to construct.
    private CGame_12100003(Builder builder) {
      super(builder);
    }
    private CGame_12100003(boolean noInit) {}
    
    private static final CGame_12100003 defaultInstance;
    public static CGame_12100003 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CGame_12100003 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.CGame_12100003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GCenter.CGame_12100003 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GCenter.CGame_12100003, Builder>
        implements com.yaowan.protobuf.game.GCenter.CGame_12100003OrBuilder {
      // Construct using com.yaowan.protobuf.game.GCenter.CGame_12100003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100003 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GCenter.CGame_12100003.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100003 build() {
        com.yaowan.protobuf.game.GCenter.CGame_12100003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GCenter.CGame_12100003 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GCenter.CGame_12100003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GCenter.CGame_12100003 buildPartial() {
        com.yaowan.protobuf.game.GCenter.CGame_12100003 result = new com.yaowan.protobuf.game.GCenter.CGame_12100003(this);
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GCenter.CGame_12100003 other) {
        if (other == com.yaowan.protobuf.game.GCenter.CGame_12100003.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.CGame_12100003)
    }
    
    static {
      defaultInstance = new CGame_12100003(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.CGame_12100003)
  }
  
  public interface NullObjOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class NullObj extends
      com.google.protobuf.GeneratedMessageLite
      implements NullObjOrBuilder {
    // Use NullObj.newBuilder() to construct.
    private NullObj(Builder builder) {
      super(builder);
    }
    private NullObj(boolean noInit) {}
    
    private static final NullObj defaultInstance;
    public static NullObj getDefaultInstance() {
      return defaultInstance;
    }
    
    public NullObj getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.NullObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GCenter.NullObj prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GCenter.NullObj, Builder>
        implements com.yaowan.protobuf.game.GCenter.NullObjOrBuilder {
      // Construct using com.yaowan.protobuf.game.GCenter.NullObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GCenter.NullObj getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GCenter.NullObj.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GCenter.NullObj build() {
        com.yaowan.protobuf.game.GCenter.NullObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GCenter.NullObj buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GCenter.NullObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GCenter.NullObj buildPartial() {
        com.yaowan.protobuf.game.GCenter.NullObj result = new com.yaowan.protobuf.game.GCenter.NullObj(this);
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GCenter.NullObj other) {
        if (other == com.yaowan.protobuf.game.GCenter.NullObj.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.NullObj)
    }
    
    static {
      defaultInstance = new NullObj(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.NullObj)
  }
  
  public interface IntVarOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 val = 1;
    boolean hasVal();
    int getVal();
  }
  public static final class IntVar extends
      com.google.protobuf.GeneratedMessageLite
      implements IntVarOrBuilder {
    // Use IntVar.newBuilder() to construct.
    private IntVar(Builder builder) {
      super(builder);
    }
    private IntVar(boolean noInit) {}
    
    private static final IntVar defaultInstance;
    public static IntVar getDefaultInstance() {
      return defaultInstance;
    }
    
    public IntVar getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 val = 1;
    public static final int VAL_FIELD_NUMBER = 1;
    private int val_;
    public boolean hasVal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getVal() {
      return val_;
    }
    
    private void initFields() {
      val_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, val_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GCenter.IntVar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GCenter.IntVar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GCenter.IntVar, Builder>
        implements com.yaowan.protobuf.game.GCenter.IntVarOrBuilder {
      // Construct using com.yaowan.protobuf.game.GCenter.IntVar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        val_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GCenter.IntVar getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GCenter.IntVar.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GCenter.IntVar build() {
        com.yaowan.protobuf.game.GCenter.IntVar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GCenter.IntVar buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GCenter.IntVar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GCenter.IntVar buildPartial() {
        com.yaowan.protobuf.game.GCenter.IntVar result = new com.yaowan.protobuf.game.GCenter.IntVar(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.val_ = val_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GCenter.IntVar other) {
        if (other == com.yaowan.protobuf.game.GCenter.IntVar.getDefaultInstance()) return this;
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              val_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 val = 1;
      private int val_ ;
      public boolean hasVal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getVal() {
        return val_;
      }
      public Builder setVal(int value) {
        bitField0_ |= 0x00000001;
        val_ = value;
        
        return this;
      }
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.IntVar)
    }
    
    static {
      defaultInstance = new IntVar(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.IntVar)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
