// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmcmd.proto

package com.yaowan.protobuf.game;

public final class GGmCmd {
  private GGmCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GMsg_11099001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 cmd = 1;
    boolean hasCmd();
    int getCmd();
    
    // optional string parameter = 2;
    boolean hasParameter();
    String getParameter();
  }
  public static final class GMsg_11099001 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_11099001OrBuilder {
    // Use GMsg_11099001.newBuilder() to construct.
    private GMsg_11099001(Builder builder) {
      super(builder);
    }
    private GMsg_11099001(boolean noInit) {}
    
    private static final GMsg_11099001 defaultInstance;
    public static GMsg_11099001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_11099001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCmd() {
      return cmd_;
    }
    
    // optional string parameter = 2;
    public static final int PARAMETER_FIELD_NUMBER = 2;
    private java.lang.Object parameter_;
    public boolean hasParameter() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getParameter() {
      java.lang.Object ref = parameter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parameter_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParameterBytes() {
      java.lang.Object ref = parameter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      cmd_ = 0;
      parameter_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParameterBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParameterBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GGmCmd.GMsg_11099001, Builder>
        implements com.yaowan.protobuf.game.GGmCmd.GMsg_11099001OrBuilder {
      // Construct using com.yaowan.protobuf.game.GGmCmd.GMsg_11099001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameter_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GGmCmd.GMsg_11099001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 build() {
        com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 buildPartial() {
        com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 result = new com.yaowan.protobuf.game.GGmCmd.GMsg_11099001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parameter_ = parameter_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GGmCmd.GMsg_11099001 other) {
        if (other == com.yaowan.protobuf.game.GGmCmd.GMsg_11099001.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasParameter()) {
          setParameter(other.getParameter());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parameter_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 cmd = 1;
      private int cmd_ ;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCmd() {
        return cmd_;
      }
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        
        return this;
      }
      
      // optional string parameter = 2;
      private java.lang.Object parameter_ = "";
      public boolean hasParameter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getParameter() {
        java.lang.Object ref = parameter_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parameter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParameter(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parameter_ = value;
        
        return this;
      }
      public Builder clearParameter() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parameter_ = getDefaultInstance().getParameter();
        
        return this;
      }
      void setParameter(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        parameter_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_11099001)
    }
    
    static {
      defaultInstance = new GMsg_11099001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_11099001)
  }
  
  public interface GMsg_12099001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class GMsg_12099001 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12099001OrBuilder {
    // Use GMsg_12099001.newBuilder() to construct.
    private GMsg_12099001(Builder builder) {
      super(builder);
    }
    private GMsg_12099001(boolean noInit) {}
    
    private static final GMsg_12099001 defaultInstance;
    public static GMsg_12099001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12099001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GGmCmd.GMsg_12099001, Builder>
        implements com.yaowan.protobuf.game.GGmCmd.GMsg_12099001OrBuilder {
      // Construct using com.yaowan.protobuf.game.GGmCmd.GMsg_12099001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GGmCmd.GMsg_12099001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 build() {
        com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 buildPartial() {
        com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 result = new com.yaowan.protobuf.game.GGmCmd.GMsg_12099001(this);
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GGmCmd.GMsg_12099001 other) {
        if (other == com.yaowan.protobuf.game.GGmCmd.GMsg_12099001.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12099001)
    }
    
    static {
      defaultInstance = new GMsg_12099001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12099001)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
