// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ranking_list.proto

package com.yaowan.protobuf.game;

public final class GRankingList {
  private GRankingList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GRankingInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int64 rid = 1;
    boolean hasRid();
    long getRid();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional int32 head = 3;
    boolean hasHead();
    int getHead();
    
    // optional bool is_vip = 4;
    boolean hasIsVip();
    boolean getIsVip();
    
    // optional int32 ranking = 5;
    boolean hasRanking();
    int getRanking();
    
    // optional int32 make_money = 6;
    boolean hasMakeMoney();
    int getMakeMoney();
    
    // optional int32 bureau_count = 7;
    boolean hasBureauCount();
    int getBureauCount();
    
    // optional int32 gold = 8;
    boolean hasGold();
    int getGold();
    
    // optional int32 type = 9;
    boolean hasType();
    int getType();
  }
  public static final class GRankingInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements GRankingInfoOrBuilder {
    // Use GRankingInfo.newBuilder() to construct.
    private GRankingInfo(Builder builder) {
      super(builder);
    }
    private GRankingInfo(boolean noInit) {}
    
    private static final GRankingInfo defaultInstance;
    public static GRankingInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public GRankingInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getRid() {
      return rid_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 head = 3;
    public static final int HEAD_FIELD_NUMBER = 3;
    private int head_;
    public boolean hasHead() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getHead() {
      return head_;
    }
    
    // optional bool is_vip = 4;
    public static final int IS_VIP_FIELD_NUMBER = 4;
    private boolean isVip_;
    public boolean hasIsVip() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsVip() {
      return isVip_;
    }
    
    // optional int32 ranking = 5;
    public static final int RANKING_FIELD_NUMBER = 5;
    private int ranking_;
    public boolean hasRanking() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getRanking() {
      return ranking_;
    }
    
    // optional int32 make_money = 6;
    public static final int MAKE_MONEY_FIELD_NUMBER = 6;
    private int makeMoney_;
    public boolean hasMakeMoney() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getMakeMoney() {
      return makeMoney_;
    }
    
    // optional int32 bureau_count = 7;
    public static final int BUREAU_COUNT_FIELD_NUMBER = 7;
    private int bureauCount_;
    public boolean hasBureauCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getBureauCount() {
      return bureauCount_;
    }
    
    // optional int32 gold = 8;
    public static final int GOLD_FIELD_NUMBER = 8;
    private int gold_;
    public boolean hasGold() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getGold() {
      return gold_;
    }
    
    // optional int32 type = 9;
    public static final int TYPE_FIELD_NUMBER = 9;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getType() {
      return type_;
    }
    
    private void initFields() {
      rid_ = 0L;
      name_ = "";
      head_ = 0;
      isVip_ = false;
      ranking_ = 0;
      makeMoney_ = 0;
      bureauCount_ = 0;
      gold_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, head_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isVip_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ranking_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, makeMoney_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, bureauCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, gold_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, type_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, head_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isVip_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ranking_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, makeMoney_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, bureauCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gold_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, type_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GRankingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GRankingList.GRankingInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GRankingList.GRankingInfo, Builder>
        implements com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder {
      // Construct using com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        head_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isVip_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        ranking_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        makeMoney_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bureauCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo build() {
        com.yaowan.protobuf.game.GRankingList.GRankingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GRankingList.GRankingInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GRankingList.GRankingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo buildPartial() {
        com.yaowan.protobuf.game.GRankingList.GRankingInfo result = new com.yaowan.protobuf.game.GRankingList.GRankingInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.head_ = head_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isVip_ = isVip_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ranking_ = ranking_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.makeMoney_ = makeMoney_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bureauCount_ = bureauCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GRankingList.GRankingInfo other) {
        if (other == com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasHead()) {
          setHead(other.getHead());
        }
        if (other.hasIsVip()) {
          setIsVip(other.getIsVip());
        }
        if (other.hasRanking()) {
          setRanking(other.getRanking());
        }
        if (other.hasMakeMoney()) {
          setMakeMoney(other.getMakeMoney());
        }
        if (other.hasBureauCount()) {
          setBureauCount(other.getBureauCount());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              head_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isVip_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ranking_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              makeMoney_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              bureauCount_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              gold_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              type_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 rid = 1;
      private long rid_ ;
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getRid() {
        return rid_;
      }
      public Builder setRid(long value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        
        return this;
      }
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0L;
        
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        
      }
      
      // optional int32 head = 3;
      private int head_ ;
      public boolean hasHead() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getHead() {
        return head_;
      }
      public Builder setHead(int value) {
        bitField0_ |= 0x00000004;
        head_ = value;
        
        return this;
      }
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000004);
        head_ = 0;
        
        return this;
      }
      
      // optional bool is_vip = 4;
      private boolean isVip_ ;
      public boolean hasIsVip() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsVip() {
        return isVip_;
      }
      public Builder setIsVip(boolean value) {
        bitField0_ |= 0x00000008;
        isVip_ = value;
        
        return this;
      }
      public Builder clearIsVip() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isVip_ = false;
        
        return this;
      }
      
      // optional int32 ranking = 5;
      private int ranking_ ;
      public boolean hasRanking() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getRanking() {
        return ranking_;
      }
      public Builder setRanking(int value) {
        bitField0_ |= 0x00000010;
        ranking_ = value;
        
        return this;
      }
      public Builder clearRanking() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ranking_ = 0;
        
        return this;
      }
      
      // optional int32 make_money = 6;
      private int makeMoney_ ;
      public boolean hasMakeMoney() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getMakeMoney() {
        return makeMoney_;
      }
      public Builder setMakeMoney(int value) {
        bitField0_ |= 0x00000020;
        makeMoney_ = value;
        
        return this;
      }
      public Builder clearMakeMoney() {
        bitField0_ = (bitField0_ & ~0x00000020);
        makeMoney_ = 0;
        
        return this;
      }
      
      // optional int32 bureau_count = 7;
      private int bureauCount_ ;
      public boolean hasBureauCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getBureauCount() {
        return bureauCount_;
      }
      public Builder setBureauCount(int value) {
        bitField0_ |= 0x00000040;
        bureauCount_ = value;
        
        return this;
      }
      public Builder clearBureauCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bureauCount_ = 0;
        
        return this;
      }
      
      // optional int32 gold = 8;
      private int gold_ ;
      public boolean hasGold() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getGold() {
        return gold_;
      }
      public Builder setGold(int value) {
        bitField0_ |= 0x00000080;
        gold_ = value;
        
        return this;
      }
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gold_ = 0;
        
        return this;
      }
      
      // optional int32 type = 9;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000100;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        type_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GRankingInfo)
    }
    
    static {
      defaultInstance = new GRankingInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GRankingInfo)
  }
  
  public interface GMsg_11018001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class GMsg_11018001 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_11018001OrBuilder {
    // Use GMsg_11018001.newBuilder() to construct.
    private GMsg_11018001(Builder builder) {
      super(builder);
    }
    private GMsg_11018001(boolean noInit) {}
    
    private static final GMsg_11018001 defaultInstance;
    public static GMsg_11018001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_11018001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_11018001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GRankingList.GMsg_11018001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GRankingList.GMsg_11018001, Builder>
        implements com.yaowan.protobuf.game.GRankingList.GMsg_11018001OrBuilder {
      // Construct using com.yaowan.protobuf.game.GRankingList.GMsg_11018001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_11018001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GRankingList.GMsg_11018001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_11018001 build() {
        com.yaowan.protobuf.game.GRankingList.GMsg_11018001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GRankingList.GMsg_11018001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GRankingList.GMsg_11018001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_11018001 buildPartial() {
        com.yaowan.protobuf.game.GRankingList.GMsg_11018001 result = new com.yaowan.protobuf.game.GRankingList.GMsg_11018001(this);
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GRankingList.GMsg_11018001 other) {
        if (other == com.yaowan.protobuf.game.GRankingList.GMsg_11018001.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_11018001)
    }
    
    static {
      defaultInstance = new GMsg_11018001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_11018001)
  }
  
  public interface GMsg_12018001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .com.yaowan.protobuf.game.GRankingInfo make_money_rank = 1;
    java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> 
        getMakeMoneyRankList();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getMakeMoneyRank(int index);
    int getMakeMoneyRankCount();
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_make_money_rank = 2;
    boolean hasSelfMakeMoneyRank();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfMakeMoneyRank();
    
    // repeated .com.yaowan.protobuf.game.GRankingInfo activity_rank = 3;
    java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> 
        getActivityRankList();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getActivityRank(int index);
    int getActivityRankCount();
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_activity_rank = 4;
    boolean hasSelfActivityRank();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfActivityRank();
    
    // repeated .com.yaowan.protobuf.game.GRankingInfo rich_rank = 5;
    java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> 
        getRichRankList();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getRichRank(int index);
    int getRichRankCount();
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_rich_rank = 6;
    boolean hasSelfRichRank();
    com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfRichRank();
  }
  public static final class GMsg_12018001 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12018001OrBuilder {
    // Use GMsg_12018001.newBuilder() to construct.
    private GMsg_12018001(Builder builder) {
      super(builder);
    }
    private GMsg_12018001(boolean noInit) {}
    
    private static final GMsg_12018001 defaultInstance;
    public static GMsg_12018001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12018001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // repeated .com.yaowan.protobuf.game.GRankingInfo make_money_rank = 1;
    public static final int MAKE_MONEY_RANK_FIELD_NUMBER = 1;
    private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> makeMoneyRank_;
    public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getMakeMoneyRankList() {
      return makeMoneyRank_;
    }
    public java.util.List<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder> 
        getMakeMoneyRankOrBuilderList() {
      return makeMoneyRank_;
    }
    public int getMakeMoneyRankCount() {
      return makeMoneyRank_.size();
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getMakeMoneyRank(int index) {
      return makeMoneyRank_.get(index);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder getMakeMoneyRankOrBuilder(
        int index) {
      return makeMoneyRank_.get(index);
    }
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_make_money_rank = 2;
    public static final int SELF_MAKE_MONEY_RANK_FIELD_NUMBER = 2;
    private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfMakeMoneyRank_;
    public boolean hasSelfMakeMoneyRank() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfMakeMoneyRank() {
      return selfMakeMoneyRank_;
    }
    
    // repeated .com.yaowan.protobuf.game.GRankingInfo activity_rank = 3;
    public static final int ACTIVITY_RANK_FIELD_NUMBER = 3;
    private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> activityRank_;
    public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getActivityRankList() {
      return activityRank_;
    }
    public java.util.List<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder> 
        getActivityRankOrBuilderList() {
      return activityRank_;
    }
    public int getActivityRankCount() {
      return activityRank_.size();
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getActivityRank(int index) {
      return activityRank_.get(index);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder getActivityRankOrBuilder(
        int index) {
      return activityRank_.get(index);
    }
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_activity_rank = 4;
    public static final int SELF_ACTIVITY_RANK_FIELD_NUMBER = 4;
    private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfActivityRank_;
    public boolean hasSelfActivityRank() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfActivityRank() {
      return selfActivityRank_;
    }
    
    // repeated .com.yaowan.protobuf.game.GRankingInfo rich_rank = 5;
    public static final int RICH_RANK_FIELD_NUMBER = 5;
    private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> richRank_;
    public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getRichRankList() {
      return richRank_;
    }
    public java.util.List<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder> 
        getRichRankOrBuilderList() {
      return richRank_;
    }
    public int getRichRankCount() {
      return richRank_.size();
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getRichRank(int index) {
      return richRank_.get(index);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfoOrBuilder getRichRankOrBuilder(
        int index) {
      return richRank_.get(index);
    }
    
    // optional .com.yaowan.protobuf.game.GRankingInfo self_rich_rank = 6;
    public static final int SELF_RICH_RANK_FIELD_NUMBER = 6;
    private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfRichRank_;
    public boolean hasSelfRichRank() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfRichRank() {
      return selfRichRank_;
    }
    
    private void initFields() {
      makeMoneyRank_ = java.util.Collections.emptyList();
      selfMakeMoneyRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      activityRank_ = java.util.Collections.emptyList();
      selfActivityRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      richRank_ = java.util.Collections.emptyList();
      selfRichRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < makeMoneyRank_.size(); i++) {
        output.writeMessage(1, makeMoneyRank_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, selfMakeMoneyRank_);
      }
      for (int i = 0; i < activityRank_.size(); i++) {
        output.writeMessage(3, activityRank_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(4, selfActivityRank_);
      }
      for (int i = 0; i < richRank_.size(); i++) {
        output.writeMessage(5, richRank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(6, selfRichRank_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < makeMoneyRank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, makeMoneyRank_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, selfMakeMoneyRank_);
      }
      for (int i = 0; i < activityRank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, activityRank_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, selfActivityRank_);
      }
      for (int i = 0; i < richRank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, richRank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, selfRichRank_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GRankingList.GMsg_12018001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GRankingList.GMsg_12018001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GRankingList.GMsg_12018001, Builder>
        implements com.yaowan.protobuf.game.GRankingList.GMsg_12018001OrBuilder {
      // Construct using com.yaowan.protobuf.game.GRankingList.GMsg_12018001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        makeMoneyRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        selfMakeMoneyRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        activityRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        selfActivityRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        richRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        selfRichRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_12018001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GRankingList.GMsg_12018001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_12018001 build() {
        com.yaowan.protobuf.game.GRankingList.GMsg_12018001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GRankingList.GMsg_12018001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GRankingList.GMsg_12018001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GRankingList.GMsg_12018001 buildPartial() {
        com.yaowan.protobuf.game.GRankingList.GMsg_12018001 result = new com.yaowan.protobuf.game.GRankingList.GMsg_12018001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          makeMoneyRank_ = java.util.Collections.unmodifiableList(makeMoneyRank_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.makeMoneyRank_ = makeMoneyRank_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.selfMakeMoneyRank_ = selfMakeMoneyRank_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          activityRank_ = java.util.Collections.unmodifiableList(activityRank_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.activityRank_ = activityRank_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.selfActivityRank_ = selfActivityRank_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          richRank_ = java.util.Collections.unmodifiableList(richRank_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.richRank_ = richRank_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000004;
        }
        result.selfRichRank_ = selfRichRank_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GRankingList.GMsg_12018001 other) {
        if (other == com.yaowan.protobuf.game.GRankingList.GMsg_12018001.getDefaultInstance()) return this;
        if (!other.makeMoneyRank_.isEmpty()) {
          if (makeMoneyRank_.isEmpty()) {
            makeMoneyRank_ = other.makeMoneyRank_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMakeMoneyRankIsMutable();
            makeMoneyRank_.addAll(other.makeMoneyRank_);
          }
          
        }
        if (other.hasSelfMakeMoneyRank()) {
          mergeSelfMakeMoneyRank(other.getSelfMakeMoneyRank());
        }
        if (!other.activityRank_.isEmpty()) {
          if (activityRank_.isEmpty()) {
            activityRank_ = other.activityRank_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureActivityRankIsMutable();
            activityRank_.addAll(other.activityRank_);
          }
          
        }
        if (other.hasSelfActivityRank()) {
          mergeSelfActivityRank(other.getSelfActivityRank());
        }
        if (!other.richRank_.isEmpty()) {
          if (richRank_.isEmpty()) {
            richRank_ = other.richRank_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRichRankIsMutable();
            richRank_.addAll(other.richRank_);
          }
          
        }
        if (other.hasSelfRichRank()) {
          mergeSelfRichRank(other.getSelfRichRank());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMakeMoneyRank(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              if (hasSelfMakeMoneyRank()) {
                subBuilder.mergeFrom(getSelfMakeMoneyRank());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSelfMakeMoneyRank(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addActivityRank(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              if (hasSelfActivityRank()) {
                subBuilder.mergeFrom(getSelfActivityRank());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSelfActivityRank(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRichRank(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder subBuilder = com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder();
              if (hasSelfRichRank()) {
                subBuilder.mergeFrom(getSelfRichRank());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSelfRichRank(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.yaowan.protobuf.game.GRankingInfo make_money_rank = 1;
      private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> makeMoneyRank_ =
        java.util.Collections.emptyList();
      private void ensureMakeMoneyRankIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          makeMoneyRank_ = new java.util.ArrayList<com.yaowan.protobuf.game.GRankingList.GRankingInfo>(makeMoneyRank_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getMakeMoneyRankList() {
        return java.util.Collections.unmodifiableList(makeMoneyRank_);
      }
      public int getMakeMoneyRankCount() {
        return makeMoneyRank_.size();
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getMakeMoneyRank(int index) {
        return makeMoneyRank_.get(index);
      }
      public Builder setMakeMoneyRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.set(index, value);
        
        return this;
      }
      public Builder setMakeMoneyRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addMakeMoneyRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.add(value);
        
        return this;
      }
      public Builder addMakeMoneyRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.add(index, value);
        
        return this;
      }
      public Builder addMakeMoneyRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.add(builderForValue.build());
        
        return this;
      }
      public Builder addMakeMoneyRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllMakeMoneyRank(
          java.lang.Iterable<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfo> values) {
        ensureMakeMoneyRankIsMutable();
        super.addAll(values, makeMoneyRank_);
        
        return this;
      }
      public Builder clearMakeMoneyRank() {
        makeMoneyRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeMakeMoneyRank(int index) {
        ensureMakeMoneyRankIsMutable();
        makeMoneyRank_.remove(index);
        
        return this;
      }
      
      // optional .com.yaowan.protobuf.game.GRankingInfo self_make_money_rank = 2;
      private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfMakeMoneyRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      public boolean hasSelfMakeMoneyRank() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfMakeMoneyRank() {
        return selfMakeMoneyRank_;
      }
      public Builder setSelfMakeMoneyRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        selfMakeMoneyRank_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setSelfMakeMoneyRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        selfMakeMoneyRank_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeSelfMakeMoneyRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            selfMakeMoneyRank_ != com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance()) {
          selfMakeMoneyRank_ =
            com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder(selfMakeMoneyRank_).mergeFrom(value).buildPartial();
        } else {
          selfMakeMoneyRank_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearSelfMakeMoneyRank() {
        selfMakeMoneyRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // repeated .com.yaowan.protobuf.game.GRankingInfo activity_rank = 3;
      private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> activityRank_ =
        java.util.Collections.emptyList();
      private void ensureActivityRankIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          activityRank_ = new java.util.ArrayList<com.yaowan.protobuf.game.GRankingList.GRankingInfo>(activityRank_);
          bitField0_ |= 0x00000004;
         }
      }
      
      public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getActivityRankList() {
        return java.util.Collections.unmodifiableList(activityRank_);
      }
      public int getActivityRankCount() {
        return activityRank_.size();
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getActivityRank(int index) {
        return activityRank_.get(index);
      }
      public Builder setActivityRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivityRankIsMutable();
        activityRank_.set(index, value);
        
        return this;
      }
      public Builder setActivityRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureActivityRankIsMutable();
        activityRank_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addActivityRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivityRankIsMutable();
        activityRank_.add(value);
        
        return this;
      }
      public Builder addActivityRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivityRankIsMutable();
        activityRank_.add(index, value);
        
        return this;
      }
      public Builder addActivityRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureActivityRankIsMutable();
        activityRank_.add(builderForValue.build());
        
        return this;
      }
      public Builder addActivityRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureActivityRankIsMutable();
        activityRank_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllActivityRank(
          java.lang.Iterable<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfo> values) {
        ensureActivityRankIsMutable();
        super.addAll(values, activityRank_);
        
        return this;
      }
      public Builder clearActivityRank() {
        activityRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      public Builder removeActivityRank(int index) {
        ensureActivityRankIsMutable();
        activityRank_.remove(index);
        
        return this;
      }
      
      // optional .com.yaowan.protobuf.game.GRankingInfo self_activity_rank = 4;
      private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfActivityRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      public boolean hasSelfActivityRank() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfActivityRank() {
        return selfActivityRank_;
      }
      public Builder setSelfActivityRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        selfActivityRank_ = value;
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setSelfActivityRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        selfActivityRank_ = builderForValue.build();
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeSelfActivityRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            selfActivityRank_ != com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance()) {
          selfActivityRank_ =
            com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder(selfActivityRank_).mergeFrom(value).buildPartial();
        } else {
          selfActivityRank_ = value;
        }
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearSelfActivityRank() {
        selfActivityRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      // repeated .com.yaowan.protobuf.game.GRankingInfo rich_rank = 5;
      private java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> richRank_ =
        java.util.Collections.emptyList();
      private void ensureRichRankIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          richRank_ = new java.util.ArrayList<com.yaowan.protobuf.game.GRankingList.GRankingInfo>(richRank_);
          bitField0_ |= 0x00000010;
         }
      }
      
      public java.util.List<com.yaowan.protobuf.game.GRankingList.GRankingInfo> getRichRankList() {
        return java.util.Collections.unmodifiableList(richRank_);
      }
      public int getRichRankCount() {
        return richRank_.size();
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getRichRank(int index) {
        return richRank_.get(index);
      }
      public Builder setRichRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRichRankIsMutable();
        richRank_.set(index, value);
        
        return this;
      }
      public Builder setRichRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureRichRankIsMutable();
        richRank_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addRichRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRichRankIsMutable();
        richRank_.add(value);
        
        return this;
      }
      public Builder addRichRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRichRankIsMutable();
        richRank_.add(index, value);
        
        return this;
      }
      public Builder addRichRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureRichRankIsMutable();
        richRank_.add(builderForValue.build());
        
        return this;
      }
      public Builder addRichRank(
          int index, com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        ensureRichRankIsMutable();
        richRank_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllRichRank(
          java.lang.Iterable<? extends com.yaowan.protobuf.game.GRankingList.GRankingInfo> values) {
        ensureRichRankIsMutable();
        super.addAll(values, richRank_);
        
        return this;
      }
      public Builder clearRichRank() {
        richRank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }
      public Builder removeRichRank(int index) {
        ensureRichRankIsMutable();
        richRank_.remove(index);
        
        return this;
      }
      
      // optional .com.yaowan.protobuf.game.GRankingInfo self_rich_rank = 6;
      private com.yaowan.protobuf.game.GRankingList.GRankingInfo selfRichRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
      public boolean hasSelfRichRank() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.yaowan.protobuf.game.GRankingList.GRankingInfo getSelfRichRank() {
        return selfRichRank_;
      }
      public Builder setSelfRichRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        selfRichRank_ = value;
        
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setSelfRichRank(
          com.yaowan.protobuf.game.GRankingList.GRankingInfo.Builder builderForValue) {
        selfRichRank_ = builderForValue.build();
        
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeSelfRichRank(com.yaowan.protobuf.game.GRankingList.GRankingInfo value) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            selfRichRank_ != com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance()) {
          selfRichRank_ =
            com.yaowan.protobuf.game.GRankingList.GRankingInfo.newBuilder(selfRichRank_).mergeFrom(value).buildPartial();
        } else {
          selfRichRank_ = value;
        }
        
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearSelfRichRank() {
        selfRichRank_ = com.yaowan.protobuf.game.GRankingList.GRankingInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12018001)
    }
    
    static {
      defaultInstance = new GMsg_12018001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12018001)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
