// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package com.yaowan.protobuf.game;

public final class GShop {
  private GShop() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GMsg_11007006OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int32 goodsId = 1;
    boolean hasGoodsId();
    int getGoodsId();
    
    // required int32 type = 2;
    boolean hasType();
    int getType();
    
    // required int32 payType = 3;
    boolean hasPayType();
    int getPayType();
    
    // optional int32 num = 4;
    boolean hasNum();
    int getNum();
    
    // optional int32 channel = 5 [default = 1];
    boolean hasChannel();
    int getChannel();
  }
  public static final class GMsg_11007006 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_11007006OrBuilder {
    // Use GMsg_11007006.newBuilder() to construct.
    private GMsg_11007006(Builder builder) {
      super(builder);
    }
    private GMsg_11007006(boolean noInit) {}
    
    private static final GMsg_11007006 defaultInstance;
    public static GMsg_11007006 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_11007006 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int32 goodsId = 1;
    public static final int GOODSID_FIELD_NUMBER = 1;
    private int goodsId_;
    public boolean hasGoodsId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGoodsId() {
      return goodsId_;
    }
    
    // required int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    // required int32 payType = 3;
    public static final int PAYTYPE_FIELD_NUMBER = 3;
    private int payType_;
    public boolean hasPayType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPayType() {
      return payType_;
    }
    
    // optional int32 num = 4;
    public static final int NUM_FIELD_NUMBER = 4;
    private int num_;
    public boolean hasNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNum() {
      return num_;
    }
    
    // optional int32 channel = 5 [default = 1];
    public static final int CHANNEL_FIELD_NUMBER = 5;
    private int channel_;
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getChannel() {
      return channel_;
    }
    
    private void initFields() {
      goodsId_ = 0;
      type_ = 0;
      payType_ = 0;
      num_ = 0;
      channel_ = 1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGoodsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, goodsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, payType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, num_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, channel_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, goodsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, payType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, num_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, channel_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_11007006 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GShop.GMsg_11007006 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GShop.GMsg_11007006, Builder>
        implements com.yaowan.protobuf.game.GShop.GMsg_11007006OrBuilder {
      // Construct using com.yaowan.protobuf.game.GShop.GMsg_11007006.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        payType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        channel_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_11007006 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GShop.GMsg_11007006.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_11007006 build() {
        com.yaowan.protobuf.game.GShop.GMsg_11007006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GShop.GMsg_11007006 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GShop.GMsg_11007006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_11007006 buildPartial() {
        com.yaowan.protobuf.game.GShop.GMsg_11007006 result = new com.yaowan.protobuf.game.GShop.GMsg_11007006(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.goodsId_ = goodsId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payType_ = payType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GShop.GMsg_11007006 other) {
        if (other == com.yaowan.protobuf.game.GShop.GMsg_11007006.getDefaultInstance()) return this;
        if (other.hasGoodsId()) {
          setGoodsId(other.getGoodsId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPayType()) {
          setPayType(other.getPayType());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGoodsId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasPayType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              goodsId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              payType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              num_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              channel_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 goodsId = 1;
      private int goodsId_ ;
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGoodsId() {
        return goodsId_;
      }
      public Builder setGoodsId(int value) {
        bitField0_ |= 0x00000001;
        goodsId_ = value;
        
        return this;
      }
      public Builder clearGoodsId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        goodsId_ = 0;
        
        return this;
      }
      
      // required int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        
        return this;
      }
      
      // required int32 payType = 3;
      private int payType_ ;
      public boolean hasPayType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPayType() {
        return payType_;
      }
      public Builder setPayType(int value) {
        bitField0_ |= 0x00000004;
        payType_ = value;
        
        return this;
      }
      public Builder clearPayType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payType_ = 0;
        
        return this;
      }
      
      // optional int32 num = 4;
      private int num_ ;
      public boolean hasNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getNum() {
        return num_;
      }
      public Builder setNum(int value) {
        bitField0_ |= 0x00000008;
        num_ = value;
        
        return this;
      }
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        num_ = 0;
        
        return this;
      }
      
      // optional int32 channel = 5 [default = 1];
      private int channel_ = 1;
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getChannel() {
        return channel_;
      }
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000010;
        channel_ = value;
        
        return this;
      }
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        channel_ = 1;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_11007006)
    }
    
    static {
      defaultInstance = new GMsg_11007006(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_11007006)
  }
  
  public interface GMsg_12007006OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 flag = 1;
    boolean hasFlag();
    int getFlag();
    
    // required int32 type = 2;
    boolean hasType();
    int getType();
    
    // optional int32 payType = 3;
    boolean hasPayType();
    int getPayType();
    
    // optional string order_id = 4;
    boolean hasOrderId();
    String getOrderId();
    
    // optional string sdk_order_id = 5;
    boolean hasSdkOrderId();
    String getSdkOrderId();
  }
  public static final class GMsg_12007006 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12007006OrBuilder {
    // Use GMsg_12007006.newBuilder() to construct.
    private GMsg_12007006(Builder builder) {
      super(builder);
    }
    private GMsg_12007006(boolean noInit) {}
    
    private static final GMsg_12007006 defaultInstance;
    public static GMsg_12007006 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12007006 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private int flag_;
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFlag() {
      return flag_;
    }
    
    // required int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    // optional int32 payType = 3;
    public static final int PAYTYPE_FIELD_NUMBER = 3;
    private int payType_;
    public boolean hasPayType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPayType() {
      return payType_;
    }
    
    // optional string order_id = 4;
    public static final int ORDER_ID_FIELD_NUMBER = 4;
    private java.lang.Object orderId_;
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          orderId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string sdk_order_id = 5;
    public static final int SDK_ORDER_ID_FIELD_NUMBER = 5;
    private java.lang.Object sdkOrderId_;
    public boolean hasSdkOrderId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSdkOrderId() {
      java.lang.Object ref = sdkOrderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sdkOrderId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSdkOrderIdBytes() {
      java.lang.Object ref = sdkOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sdkOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      flag_ = 0;
      type_ = 0;
      payType_ = 0;
      orderId_ = "";
      sdkOrderId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, payType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSdkOrderIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, payType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSdkOrderIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007006 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GShop.GMsg_12007006 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GShop.GMsg_12007006, Builder>
        implements com.yaowan.protobuf.game.GShop.GMsg_12007006OrBuilder {
      // Construct using com.yaowan.protobuf.game.GShop.GMsg_12007006.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        payType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sdkOrderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007006 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GShop.GMsg_12007006.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007006 build() {
        com.yaowan.protobuf.game.GShop.GMsg_12007006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GShop.GMsg_12007006 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GShop.GMsg_12007006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007006 buildPartial() {
        com.yaowan.protobuf.game.GShop.GMsg_12007006 result = new com.yaowan.protobuf.game.GShop.GMsg_12007006(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payType_ = payType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sdkOrderId_ = sdkOrderId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GShop.GMsg_12007006 other) {
        if (other == com.yaowan.protobuf.game.GShop.GMsg_12007006.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPayType()) {
          setPayType(other.getPayType());
        }
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasSdkOrderId()) {
          setSdkOrderId(other.getSdkOrderId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              payType_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              orderId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sdkOrderId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 flag = 1;
      private int flag_ ;
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFlag() {
        return flag_;
      }
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        
        return this;
      }
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        
        return this;
      }
      
      // required int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        
        return this;
      }
      
      // optional int32 payType = 3;
      private int payType_ ;
      public boolean hasPayType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPayType() {
        return payType_;
      }
      public Builder setPayType(int value) {
        bitField0_ |= 0x00000004;
        payType_ = value;
        
        return this;
      }
      public Builder clearPayType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payType_ = 0;
        
        return this;
      }
      
      // optional string order_id = 4;
      private java.lang.Object orderId_ = "";
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrderId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        orderId_ = value;
        
        return this;
      }
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        orderId_ = getDefaultInstance().getOrderId();
        
        return this;
      }
      void setOrderId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        orderId_ = value;
        
      }
      
      // optional string sdk_order_id = 5;
      private java.lang.Object sdkOrderId_ = "";
      public boolean hasSdkOrderId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSdkOrderId() {
        java.lang.Object ref = sdkOrderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sdkOrderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSdkOrderId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sdkOrderId_ = value;
        
        return this;
      }
      public Builder clearSdkOrderId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sdkOrderId_ = getDefaultInstance().getSdkOrderId();
        
        return this;
      }
      void setSdkOrderId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        sdkOrderId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12007006)
    }
    
    static {
      defaultInstance = new GMsg_12007006(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12007006)
  }
  
  public interface GMsg_12007007OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 flag = 1;
    boolean hasFlag();
    int getFlag();
    
    // optional string hasChargeInfo = 2;
    boolean hasHasChargeInfo();
    String getHasChargeInfo();
  }
  public static final class GMsg_12007007 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12007007OrBuilder {
    // Use GMsg_12007007.newBuilder() to construct.
    private GMsg_12007007(Builder builder) {
      super(builder);
    }
    private GMsg_12007007(boolean noInit) {}
    
    private static final GMsg_12007007 defaultInstance;
    public static GMsg_12007007 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12007007 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private int flag_;
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFlag() {
      return flag_;
    }
    
    // optional string hasChargeInfo = 2;
    public static final int HASCHARGEINFO_FIELD_NUMBER = 2;
    private java.lang.Object hasChargeInfo_;
    public boolean hasHasChargeInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getHasChargeInfo() {
      java.lang.Object ref = hasChargeInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hasChargeInfo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHasChargeInfoBytes() {
      java.lang.Object ref = hasChargeInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hasChargeInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      flag_ = 0;
      hasChargeInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHasChargeInfoBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHasChargeInfoBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007007 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GShop.GMsg_12007007 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GShop.GMsg_12007007, Builder>
        implements com.yaowan.protobuf.game.GShop.GMsg_12007007OrBuilder {
      // Construct using com.yaowan.protobuf.game.GShop.GMsg_12007007.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        hasChargeInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007007 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GShop.GMsg_12007007.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007007 build() {
        com.yaowan.protobuf.game.GShop.GMsg_12007007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GShop.GMsg_12007007 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GShop.GMsg_12007007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007007 buildPartial() {
        com.yaowan.protobuf.game.GShop.GMsg_12007007 result = new com.yaowan.protobuf.game.GShop.GMsg_12007007(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hasChargeInfo_ = hasChargeInfo_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GShop.GMsg_12007007 other) {
        if (other == com.yaowan.protobuf.game.GShop.GMsg_12007007.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasHasChargeInfo()) {
          setHasChargeInfo(other.getHasChargeInfo());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              hasChargeInfo_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 flag = 1;
      private int flag_ ;
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFlag() {
        return flag_;
      }
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        
        return this;
      }
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        
        return this;
      }
      
      // optional string hasChargeInfo = 2;
      private java.lang.Object hasChargeInfo_ = "";
      public boolean hasHasChargeInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getHasChargeInfo() {
        java.lang.Object ref = hasChargeInfo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hasChargeInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHasChargeInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hasChargeInfo_ = value;
        
        return this;
      }
      public Builder clearHasChargeInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hasChargeInfo_ = getDefaultInstance().getHasChargeInfo();
        
        return this;
      }
      void setHasChargeInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        hasChargeInfo_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12007007)
    }
    
    static {
      defaultInstance = new GMsg_12007007(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12007007)
  }
  
  public interface GMsg_12007008OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 flag = 1;
    boolean hasFlag();
    int getFlag();
    
    // optional int32 vipTime = 2;
    boolean hasVipTime();
    int getVipTime();
    
    // optional int32 vipleftTime = 3;
    boolean hasVipleftTime();
    int getVipleftTime();
  }
  public static final class GMsg_12007008 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12007008OrBuilder {
    // Use GMsg_12007008.newBuilder() to construct.
    private GMsg_12007008(Builder builder) {
      super(builder);
    }
    private GMsg_12007008(boolean noInit) {}
    
    private static final GMsg_12007008 defaultInstance;
    public static GMsg_12007008 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12007008 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private int flag_;
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFlag() {
      return flag_;
    }
    
    // optional int32 vipTime = 2;
    public static final int VIPTIME_FIELD_NUMBER = 2;
    private int vipTime_;
    public boolean hasVipTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getVipTime() {
      return vipTime_;
    }
    
    // optional int32 vipleftTime = 3;
    public static final int VIPLEFTTIME_FIELD_NUMBER = 3;
    private int vipleftTime_;
    public boolean hasVipleftTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getVipleftTime() {
      return vipleftTime_;
    }
    
    private void initFields() {
      flag_ = 0;
      vipTime_ = 0;
      vipleftTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, vipTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, vipleftTime_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, vipTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vipleftTime_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007008 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GShop.GMsg_12007008 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GShop.GMsg_12007008, Builder>
        implements com.yaowan.protobuf.game.GShop.GMsg_12007008OrBuilder {
      // Construct using com.yaowan.protobuf.game.GShop.GMsg_12007008.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vipTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        vipleftTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007008 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GShop.GMsg_12007008.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007008 build() {
        com.yaowan.protobuf.game.GShop.GMsg_12007008 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GShop.GMsg_12007008 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GShop.GMsg_12007008 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007008 buildPartial() {
        com.yaowan.protobuf.game.GShop.GMsg_12007008 result = new com.yaowan.protobuf.game.GShop.GMsg_12007008(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vipTime_ = vipTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.vipleftTime_ = vipleftTime_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GShop.GMsg_12007008 other) {
        if (other == com.yaowan.protobuf.game.GShop.GMsg_12007008.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasVipTime()) {
          setVipTime(other.getVipTime());
        }
        if (other.hasVipleftTime()) {
          setVipleftTime(other.getVipleftTime());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              vipTime_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              vipleftTime_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 flag = 1;
      private int flag_ ;
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFlag() {
        return flag_;
      }
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        
        return this;
      }
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        
        return this;
      }
      
      // optional int32 vipTime = 2;
      private int vipTime_ ;
      public boolean hasVipTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getVipTime() {
        return vipTime_;
      }
      public Builder setVipTime(int value) {
        bitField0_ |= 0x00000002;
        vipTime_ = value;
        
        return this;
      }
      public Builder clearVipTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vipTime_ = 0;
        
        return this;
      }
      
      // optional int32 vipleftTime = 3;
      private int vipleftTime_ ;
      public boolean hasVipleftTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getVipleftTime() {
        return vipleftTime_;
      }
      public Builder setVipleftTime(int value) {
        bitField0_ |= 0x00000004;
        vipleftTime_ = value;
        
        return this;
      }
      public Builder clearVipleftTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vipleftTime_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12007008)
    }
    
    static {
      defaultInstance = new GMsg_12007008(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12007008)
  }
  
  public interface GMsg_12007009OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int32 goodsId = 1;
    boolean hasGoodsId();
    int getGoodsId();
  }
  public static final class GMsg_12007009 extends
      com.google.protobuf.GeneratedMessageLite
      implements GMsg_12007009OrBuilder {
    // Use GMsg_12007009.newBuilder() to construct.
    private GMsg_12007009(Builder builder) {
      super(builder);
    }
    private GMsg_12007009(boolean noInit) {}
    
    private static final GMsg_12007009 defaultInstance;
    public static GMsg_12007009 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMsg_12007009 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int32 goodsId = 1;
    public static final int GOODSID_FIELD_NUMBER = 1;
    private int goodsId_;
    public boolean hasGoodsId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGoodsId() {
      return goodsId_;
    }
    
    private void initFields() {
      goodsId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGoodsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, goodsId_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, goodsId_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.game.GShop.GMsg_12007009 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.game.GShop.GMsg_12007009 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.game.GShop.GMsg_12007009, Builder>
        implements com.yaowan.protobuf.game.GShop.GMsg_12007009OrBuilder {
      // Construct using com.yaowan.protobuf.game.GShop.GMsg_12007009.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007009 getDefaultInstanceForType() {
        return com.yaowan.protobuf.game.GShop.GMsg_12007009.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007009 build() {
        com.yaowan.protobuf.game.GShop.GMsg_12007009 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.game.GShop.GMsg_12007009 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.game.GShop.GMsg_12007009 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.game.GShop.GMsg_12007009 buildPartial() {
        com.yaowan.protobuf.game.GShop.GMsg_12007009 result = new com.yaowan.protobuf.game.GShop.GMsg_12007009(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.goodsId_ = goodsId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.game.GShop.GMsg_12007009 other) {
        if (other == com.yaowan.protobuf.game.GShop.GMsg_12007009.getDefaultInstance()) return this;
        if (other.hasGoodsId()) {
          setGoodsId(other.getGoodsId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGoodsId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              goodsId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 goodsId = 1;
      private int goodsId_ ;
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGoodsId() {
        return goodsId_;
      }
      public Builder setGoodsId(int value) {
        bitField0_ |= 0x00000001;
        goodsId_ = value;
        
        return this;
      }
      public Builder clearGoodsId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        goodsId_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.game.GMsg_12007009)
    }
    
    static {
      defaultInstance = new GMsg_12007009(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.game.GMsg_12007009)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
