// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cregister.proto

package com.yaowan.protobuf.center;

public final class CRegister {
  private CRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CServerInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // optional int32 platform = 2;
    boolean hasPlatform();
    int getPlatform();
    
    // required string host = 3;
    boolean hasHost();
    String getHost();
    
    // required int32 port = 4;
    boolean hasPort();
    int getPort();
    
    // optional int32 http_port = 5;
    boolean hasHttpPort();
    int getHttpPort();
    
    // optional string mysql_host = 6;
    boolean hasMysqlHost();
    String getMysqlHost();
    
    // optional int32 mysql_port = 7;
    boolean hasMysqlPort();
    int getMysqlPort();
    
    // optional string mysql_user = 8;
    boolean hasMysqlUser();
    String getMysqlUser();
    
    // optional string mysql_passwd = 9;
    boolean hasMysqlPasswd();
    String getMysqlPasswd();
    
    // optional string actor_table = 10;
    boolean hasActorTable();
    String getActorTable();
    
    // optional string log_table = 11;
    boolean hasLogTable();
    String getLogTable();
    
    // optional string name = 12;
    boolean hasName();
    String getName();
    
    // repeated int32 gameTypes = 13;
    java.util.List<java.lang.Integer> getGameTypesList();
    int getGameTypesCount();
    int getGameTypes(int index);
  }
  public static final class CServerInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements CServerInfoOrBuilder {
    // Use CServerInfo.newBuilder() to construct.
    private CServerInfo(Builder builder) {
      super(builder);
    }
    private CServerInfo(boolean noInit) {}
    
    private static final CServerInfo defaultInstance;
    public static CServerInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public CServerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // optional int32 platform = 2;
    public static final int PLATFORM_FIELD_NUMBER = 2;
    private int platform_;
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPlatform() {
      return platform_;
    }
    
    // required string host = 3;
    public static final int HOST_FIELD_NUMBER = 3;
    private java.lang.Object host_;
    public boolean hasHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          host_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 port = 4;
    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPort() {
      return port_;
    }
    
    // optional int32 http_port = 5;
    public static final int HTTP_PORT_FIELD_NUMBER = 5;
    private int httpPort_;
    public boolean hasHttpPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getHttpPort() {
      return httpPort_;
    }
    
    // optional string mysql_host = 6;
    public static final int MYSQL_HOST_FIELD_NUMBER = 6;
    private java.lang.Object mysqlHost_;
    public boolean hasMysqlHost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getMysqlHost() {
      java.lang.Object ref = mysqlHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mysqlHost_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMysqlHostBytes() {
      java.lang.Object ref = mysqlHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mysqlHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 mysql_port = 7;
    public static final int MYSQL_PORT_FIELD_NUMBER = 7;
    private int mysqlPort_;
    public boolean hasMysqlPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getMysqlPort() {
      return mysqlPort_;
    }
    
    // optional string mysql_user = 8;
    public static final int MYSQL_USER_FIELD_NUMBER = 8;
    private java.lang.Object mysqlUser_;
    public boolean hasMysqlUser() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getMysqlUser() {
      java.lang.Object ref = mysqlUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mysqlUser_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMysqlUserBytes() {
      java.lang.Object ref = mysqlUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mysqlUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mysql_passwd = 9;
    public static final int MYSQL_PASSWD_FIELD_NUMBER = 9;
    private java.lang.Object mysqlPasswd_;
    public boolean hasMysqlPasswd() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getMysqlPasswd() {
      java.lang.Object ref = mysqlPasswd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mysqlPasswd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMysqlPasswdBytes() {
      java.lang.Object ref = mysqlPasswd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mysqlPasswd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string actor_table = 10;
    public static final int ACTOR_TABLE_FIELD_NUMBER = 10;
    private java.lang.Object actorTable_;
    public boolean hasActorTable() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getActorTable() {
      java.lang.Object ref = actorTable_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actorTable_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActorTableBytes() {
      java.lang.Object ref = actorTable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actorTable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string log_table = 11;
    public static final int LOG_TABLE_FIELD_NUMBER = 11;
    private java.lang.Object logTable_;
    public boolean hasLogTable() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getLogTable() {
      java.lang.Object ref = logTable_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          logTable_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogTableBytes() {
      java.lang.Object ref = logTable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        logTable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 12;
    public static final int NAME_FIELD_NUMBER = 12;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated int32 gameTypes = 13;
    public static final int GAMETYPES_FIELD_NUMBER = 13;
    private java.util.List<java.lang.Integer> gameTypes_;
    public java.util.List<java.lang.Integer>
        getGameTypesList() {
      return gameTypes_;
    }
    public int getGameTypesCount() {
      return gameTypes_.size();
    }
    public int getGameTypes(int index) {
      return gameTypes_.get(index);
    }
    
    private void initFields() {
      id_ = 0;
      platform_ = 0;
      host_ = "";
      port_ = 0;
      httpPort_ = 0;
      mysqlHost_ = "";
      mysqlPort_ = 0;
      mysqlUser_ = "";
      mysqlPasswd_ = "";
      actorTable_ = "";
      logTable_ = "";
      name_ = "";
      gameTypes_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, platform_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, httpPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMysqlHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, mysqlPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMysqlUserBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMysqlPasswdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getActorTableBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getLogTableBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getNameBytes());
      }
      for (int i = 0; i < gameTypes_.size(); i++) {
        output.writeInt32(13, gameTypes_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, platform_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, httpPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMysqlHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, mysqlPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMysqlUserBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMysqlPasswdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getActorTableBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getLogTableBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gameTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(gameTypes_.get(i));
        }
        size += dataSize;
        size += 1 * getGameTypesList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.center.CRegister.CServerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.center.CRegister.CServerInfo, Builder>
        implements com.yaowan.protobuf.center.CRegister.CServerInfoOrBuilder {
      // Construct using com.yaowan.protobuf.center.CRegister.CServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        platform_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        httpPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        mysqlHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        mysqlPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        mysqlUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        mysqlPasswd_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        actorTable_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        logTable_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        gameTypes_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.center.CRegister.CServerInfo getDefaultInstanceForType() {
        return com.yaowan.protobuf.center.CRegister.CServerInfo.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.center.CRegister.CServerInfo build() {
        com.yaowan.protobuf.center.CRegister.CServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.center.CRegister.CServerInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.center.CRegister.CServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.center.CRegister.CServerInfo buildPartial() {
        com.yaowan.protobuf.center.CRegister.CServerInfo result = new com.yaowan.protobuf.center.CRegister.CServerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.httpPort_ = httpPort_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mysqlHost_ = mysqlHost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mysqlPort_ = mysqlPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.mysqlUser_ = mysqlUser_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.mysqlPasswd_ = mysqlPasswd_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.actorTable_ = actorTable_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.logTable_ = logTable_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          gameTypes_ = java.util.Collections.unmodifiableList(gameTypes_);
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.gameTypes_ = gameTypes_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.center.CRegister.CServerInfo other) {
        if (other == com.yaowan.protobuf.center.CRegister.CServerInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasHost()) {
          setHost(other.getHost());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasHttpPort()) {
          setHttpPort(other.getHttpPort());
        }
        if (other.hasMysqlHost()) {
          setMysqlHost(other.getMysqlHost());
        }
        if (other.hasMysqlPort()) {
          setMysqlPort(other.getMysqlPort());
        }
        if (other.hasMysqlUser()) {
          setMysqlUser(other.getMysqlUser());
        }
        if (other.hasMysqlPasswd()) {
          setMysqlPasswd(other.getMysqlPasswd());
        }
        if (other.hasActorTable()) {
          setActorTable(other.getActorTable());
        }
        if (other.hasLogTable()) {
          setLogTable(other.getLogTable());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.gameTypes_.isEmpty()) {
          if (gameTypes_.isEmpty()) {
            gameTypes_ = other.gameTypes_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureGameTypesIsMutable();
            gameTypes_.addAll(other.gameTypes_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              platform_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              host_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              httpPort_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              mysqlHost_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              mysqlPort_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              mysqlUser_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              mysqlPasswd_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              actorTable_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              logTable_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              name_ = input.readBytes();
              break;
            }
            case 104: {
              ensureGameTypesIsMutable();
              gameTypes_.add(input.readInt32());
              break;
            }
            case 106: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGameTypes(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        
        return this;
      }
      
      // optional int32 platform = 2;
      private int platform_ ;
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPlatform() {
        return platform_;
      }
      public Builder setPlatform(int value) {
        bitField0_ |= 0x00000002;
        platform_ = value;
        
        return this;
      }
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000002);
        platform_ = 0;
        
        return this;
      }
      
      // required string host = 3;
      private java.lang.Object host_ = "";
      public boolean hasHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHost(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        host_ = value;
        
        return this;
      }
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        host_ = getDefaultInstance().getHost();
        
        return this;
      }
      void setHost(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        host_ = value;
        
      }
      
      // required int32 port = 4;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        
        return this;
      }
      
      // optional int32 http_port = 5;
      private int httpPort_ ;
      public boolean hasHttpPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getHttpPort() {
        return httpPort_;
      }
      public Builder setHttpPort(int value) {
        bitField0_ |= 0x00000010;
        httpPort_ = value;
        
        return this;
      }
      public Builder clearHttpPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        httpPort_ = 0;
        
        return this;
      }
      
      // optional string mysql_host = 6;
      private java.lang.Object mysqlHost_ = "";
      public boolean hasMysqlHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getMysqlHost() {
        java.lang.Object ref = mysqlHost_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mysqlHost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMysqlHost(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        mysqlHost_ = value;
        
        return this;
      }
      public Builder clearMysqlHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mysqlHost_ = getDefaultInstance().getMysqlHost();
        
        return this;
      }
      void setMysqlHost(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        mysqlHost_ = value;
        
      }
      
      // optional int32 mysql_port = 7;
      private int mysqlPort_ ;
      public boolean hasMysqlPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getMysqlPort() {
        return mysqlPort_;
      }
      public Builder setMysqlPort(int value) {
        bitField0_ |= 0x00000040;
        mysqlPort_ = value;
        
        return this;
      }
      public Builder clearMysqlPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mysqlPort_ = 0;
        
        return this;
      }
      
      // optional string mysql_user = 8;
      private java.lang.Object mysqlUser_ = "";
      public boolean hasMysqlUser() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getMysqlUser() {
        java.lang.Object ref = mysqlUser_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mysqlUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMysqlUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        mysqlUser_ = value;
        
        return this;
      }
      public Builder clearMysqlUser() {
        bitField0_ = (bitField0_ & ~0x00000080);
        mysqlUser_ = getDefaultInstance().getMysqlUser();
        
        return this;
      }
      void setMysqlUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        mysqlUser_ = value;
        
      }
      
      // optional string mysql_passwd = 9;
      private java.lang.Object mysqlPasswd_ = "";
      public boolean hasMysqlPasswd() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getMysqlPasswd() {
        java.lang.Object ref = mysqlPasswd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mysqlPasswd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMysqlPasswd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        mysqlPasswd_ = value;
        
        return this;
      }
      public Builder clearMysqlPasswd() {
        bitField0_ = (bitField0_ & ~0x00000100);
        mysqlPasswd_ = getDefaultInstance().getMysqlPasswd();
        
        return this;
      }
      void setMysqlPasswd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        mysqlPasswd_ = value;
        
      }
      
      // optional string actor_table = 10;
      private java.lang.Object actorTable_ = "";
      public boolean hasActorTable() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getActorTable() {
        java.lang.Object ref = actorTable_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actorTable_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActorTable(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        actorTable_ = value;
        
        return this;
      }
      public Builder clearActorTable() {
        bitField0_ = (bitField0_ & ~0x00000200);
        actorTable_ = getDefaultInstance().getActorTable();
        
        return this;
      }
      void setActorTable(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        actorTable_ = value;
        
      }
      
      // optional string log_table = 11;
      private java.lang.Object logTable_ = "";
      public boolean hasLogTable() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getLogTable() {
        java.lang.Object ref = logTable_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          logTable_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLogTable(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        logTable_ = value;
        
        return this;
      }
      public Builder clearLogTable() {
        bitField0_ = (bitField0_ & ~0x00000400);
        logTable_ = getDefaultInstance().getLogTable();
        
        return this;
      }
      void setLogTable(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        logTable_ = value;
        
      }
      
      // optional string name = 12;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000800);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        name_ = value;
        
      }
      
      // repeated int32 gameTypes = 13;
      private java.util.List<java.lang.Integer> gameTypes_ = java.util.Collections.emptyList();;
      private void ensureGameTypesIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          gameTypes_ = new java.util.ArrayList<java.lang.Integer>(gameTypes_);
          bitField0_ |= 0x00001000;
         }
      }
      public java.util.List<java.lang.Integer>
          getGameTypesList() {
        return java.util.Collections.unmodifiableList(gameTypes_);
      }
      public int getGameTypesCount() {
        return gameTypes_.size();
      }
      public int getGameTypes(int index) {
        return gameTypes_.get(index);
      }
      public Builder setGameTypes(
          int index, int value) {
        ensureGameTypesIsMutable();
        gameTypes_.set(index, value);
        
        return this;
      }
      public Builder addGameTypes(int value) {
        ensureGameTypesIsMutable();
        gameTypes_.add(value);
        
        return this;
      }
      public Builder addAllGameTypes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGameTypesIsMutable();
        super.addAll(values, gameTypes_);
        
        return this;
      }
      public Builder clearGameTypes() {
        gameTypes_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00001000);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.center.CServerInfo)
    }
    
    static {
      defaultInstance = new CServerInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.center.CServerInfo)
  }
  
  public interface CMsg_21001001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 server_id = 1;
    boolean hasServerId();
    int getServerId();
    
    // repeated int32 gameTypes = 2;
    java.util.List<java.lang.Integer> getGameTypesList();
    int getGameTypesCount();
    int getGameTypes(int index);
    
    // optional int32 online = 3;
    boolean hasOnline();
    int getOnline();
  }
  public static final class CMsg_21001001 extends
      com.google.protobuf.GeneratedMessageLite
      implements CMsg_21001001OrBuilder {
    // Use CMsg_21001001.newBuilder() to construct.
    private CMsg_21001001(Builder builder) {
      super(builder);
    }
    private CMsg_21001001(boolean noInit) {}
    
    private static final CMsg_21001001 defaultInstance;
    public static CMsg_21001001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CMsg_21001001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 server_id = 1;
    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    // repeated int32 gameTypes = 2;
    public static final int GAMETYPES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> gameTypes_;
    public java.util.List<java.lang.Integer>
        getGameTypesList() {
      return gameTypes_;
    }
    public int getGameTypesCount() {
      return gameTypes_.size();
    }
    public int getGameTypes(int index) {
      return gameTypes_.get(index);
    }
    
    // optional int32 online = 3;
    public static final int ONLINE_FIELD_NUMBER = 3;
    private int online_;
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOnline() {
      return online_;
    }
    
    private void initFields() {
      serverId_ = 0;
      gameTypes_ = java.util.Collections.emptyList();;
      online_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      for (int i = 0; i < gameTypes_.size(); i++) {
        output.writeInt32(2, gameTypes_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, online_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gameTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(gameTypes_.get(i));
        }
        size += dataSize;
        size += 1 * getGameTypesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, online_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.center.CRegister.CMsg_21001001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.center.CRegister.CMsg_21001001, Builder>
        implements com.yaowan.protobuf.center.CRegister.CMsg_21001001OrBuilder {
      // Construct using com.yaowan.protobuf.center.CRegister.CMsg_21001001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        gameTypes_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        online_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.center.CRegister.CMsg_21001001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001001 build() {
        com.yaowan.protobuf.center.CRegister.CMsg_21001001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.center.CRegister.CMsg_21001001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.center.CRegister.CMsg_21001001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001001 buildPartial() {
        com.yaowan.protobuf.center.CRegister.CMsg_21001001 result = new com.yaowan.protobuf.center.CRegister.CMsg_21001001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          gameTypes_ = java.util.Collections.unmodifiableList(gameTypes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.gameTypes_ = gameTypes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.online_ = online_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.center.CRegister.CMsg_21001001 other) {
        if (other == com.yaowan.protobuf.center.CRegister.CMsg_21001001.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (!other.gameTypes_.isEmpty()) {
          if (gameTypes_.isEmpty()) {
            gameTypes_ = other.gameTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGameTypesIsMutable();
            gameTypes_.addAll(other.gameTypes_);
          }
          
        }
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 16: {
              ensureGameTypesIsMutable();
              gameTypes_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGameTypes(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              online_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 server_id = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        
        return this;
      }
      
      // repeated int32 gameTypes = 2;
      private java.util.List<java.lang.Integer> gameTypes_ = java.util.Collections.emptyList();;
      private void ensureGameTypesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          gameTypes_ = new java.util.ArrayList<java.lang.Integer>(gameTypes_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getGameTypesList() {
        return java.util.Collections.unmodifiableList(gameTypes_);
      }
      public int getGameTypesCount() {
        return gameTypes_.size();
      }
      public int getGameTypes(int index) {
        return gameTypes_.get(index);
      }
      public Builder setGameTypes(
          int index, int value) {
        ensureGameTypesIsMutable();
        gameTypes_.set(index, value);
        
        return this;
      }
      public Builder addGameTypes(int value) {
        ensureGameTypesIsMutable();
        gameTypes_.add(value);
        
        return this;
      }
      public Builder addAllGameTypes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGameTypesIsMutable();
        super.addAll(values, gameTypes_);
        
        return this;
      }
      public Builder clearGameTypes() {
        gameTypes_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      
      // optional int32 online = 3;
      private int online_ ;
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getOnline() {
        return online_;
      }
      public Builder setOnline(int value) {
        bitField0_ |= 0x00000004;
        online_ = value;
        
        return this;
      }
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000004);
        online_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.center.CMsg_21001001)
    }
    
    static {
      defaultInstance = new CMsg_21001001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.center.CMsg_21001001)
  }
  
  public interface CMsg_22001001OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .com.yaowan.protobuf.center.CServerInfo servers = 1;
    java.util.List<com.yaowan.protobuf.center.CRegister.CServerInfo> 
        getServersList();
    com.yaowan.protobuf.center.CRegister.CServerInfo getServers(int index);
    int getServersCount();
  }
  public static final class CMsg_22001001 extends
      com.google.protobuf.GeneratedMessageLite
      implements CMsg_22001001OrBuilder {
    // Use CMsg_22001001.newBuilder() to construct.
    private CMsg_22001001(Builder builder) {
      super(builder);
    }
    private CMsg_22001001(boolean noInit) {}
    
    private static final CMsg_22001001 defaultInstance;
    public static CMsg_22001001 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CMsg_22001001 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .com.yaowan.protobuf.center.CServerInfo servers = 1;
    public static final int SERVERS_FIELD_NUMBER = 1;
    private java.util.List<com.yaowan.protobuf.center.CRegister.CServerInfo> servers_;
    public java.util.List<com.yaowan.protobuf.center.CRegister.CServerInfo> getServersList() {
      return servers_;
    }
    public java.util.List<? extends com.yaowan.protobuf.center.CRegister.CServerInfoOrBuilder> 
        getServersOrBuilderList() {
      return servers_;
    }
    public int getServersCount() {
      return servers_.size();
    }
    public com.yaowan.protobuf.center.CRegister.CServerInfo getServers(int index) {
      return servers_.get(index);
    }
    public com.yaowan.protobuf.center.CRegister.CServerInfoOrBuilder getServersOrBuilder(
        int index) {
      return servers_.get(index);
    }
    
    private void initFields() {
      servers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getServersCount(); i++) {
        if (!getServers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < servers_.size(); i++) {
        output.writeMessage(1, servers_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < servers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, servers_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.center.CRegister.CMsg_22001001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.center.CRegister.CMsg_22001001, Builder>
        implements com.yaowan.protobuf.center.CRegister.CMsg_22001001OrBuilder {
      // Construct using com.yaowan.protobuf.center.CRegister.CMsg_22001001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001001 getDefaultInstanceForType() {
        return com.yaowan.protobuf.center.CRegister.CMsg_22001001.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001001 build() {
        com.yaowan.protobuf.center.CRegister.CMsg_22001001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.center.CRegister.CMsg_22001001 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.center.CRegister.CMsg_22001001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001001 buildPartial() {
        com.yaowan.protobuf.center.CRegister.CMsg_22001001 result = new com.yaowan.protobuf.center.CRegister.CMsg_22001001(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          servers_ = java.util.Collections.unmodifiableList(servers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.servers_ = servers_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.center.CRegister.CMsg_22001001 other) {
        if (other == com.yaowan.protobuf.center.CRegister.CMsg_22001001.getDefaultInstance()) return this;
        if (!other.servers_.isEmpty()) {
          if (servers_.isEmpty()) {
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServersIsMutable();
            servers_.addAll(other.servers_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getServersCount(); i++) {
          if (!getServers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.yaowan.protobuf.center.CRegister.CServerInfo.Builder subBuilder = com.yaowan.protobuf.center.CRegister.CServerInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addServers(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.yaowan.protobuf.center.CServerInfo servers = 1;
      private java.util.List<com.yaowan.protobuf.center.CRegister.CServerInfo> servers_ =
        java.util.Collections.emptyList();
      private void ensureServersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          servers_ = new java.util.ArrayList<com.yaowan.protobuf.center.CRegister.CServerInfo>(servers_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.yaowan.protobuf.center.CRegister.CServerInfo> getServersList() {
        return java.util.Collections.unmodifiableList(servers_);
      }
      public int getServersCount() {
        return servers_.size();
      }
      public com.yaowan.protobuf.center.CRegister.CServerInfo getServers(int index) {
        return servers_.get(index);
      }
      public Builder setServers(
          int index, com.yaowan.protobuf.center.CRegister.CServerInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.set(index, value);
        
        return this;
      }
      public Builder setServers(
          int index, com.yaowan.protobuf.center.CRegister.CServerInfo.Builder builderForValue) {
        ensureServersIsMutable();
        servers_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addServers(com.yaowan.protobuf.center.CRegister.CServerInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(value);
        
        return this;
      }
      public Builder addServers(
          int index, com.yaowan.protobuf.center.CRegister.CServerInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(index, value);
        
        return this;
      }
      public Builder addServers(
          com.yaowan.protobuf.center.CRegister.CServerInfo.Builder builderForValue) {
        ensureServersIsMutable();
        servers_.add(builderForValue.build());
        
        return this;
      }
      public Builder addServers(
          int index, com.yaowan.protobuf.center.CRegister.CServerInfo.Builder builderForValue) {
        ensureServersIsMutable();
        servers_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllServers(
          java.lang.Iterable<? extends com.yaowan.protobuf.center.CRegister.CServerInfo> values) {
        ensureServersIsMutable();
        super.addAll(values, servers_);
        
        return this;
      }
      public Builder clearServers() {
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeServers(int index) {
        ensureServersIsMutable();
        servers_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.center.CMsg_22001001)
    }
    
    static {
      defaultInstance = new CMsg_22001001(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.center.CMsg_22001001)
  }
  
  public interface CMsg_21001003OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional int32 server_id = 1;
    boolean hasServerId();
    int getServerId();
  }
  public static final class CMsg_21001003 extends
      com.google.protobuf.GeneratedMessageLite
      implements CMsg_21001003OrBuilder {
    // Use CMsg_21001003.newBuilder() to construct.
    private CMsg_21001003(Builder builder) {
      super(builder);
    }
    private CMsg_21001003(boolean noInit) {}
    
    private static final CMsg_21001003 defaultInstance;
    public static CMsg_21001003 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CMsg_21001003 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional int32 server_id = 1;
    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    private void initFields() {
      serverId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_21001003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.center.CRegister.CMsg_21001003 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.center.CRegister.CMsg_21001003, Builder>
        implements com.yaowan.protobuf.center.CRegister.CMsg_21001003OrBuilder {
      // Construct using com.yaowan.protobuf.center.CRegister.CMsg_21001003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001003 getDefaultInstanceForType() {
        return com.yaowan.protobuf.center.CRegister.CMsg_21001003.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001003 build() {
        com.yaowan.protobuf.center.CRegister.CMsg_21001003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.center.CRegister.CMsg_21001003 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.center.CRegister.CMsg_21001003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_21001003 buildPartial() {
        com.yaowan.protobuf.center.CRegister.CMsg_21001003 result = new com.yaowan.protobuf.center.CRegister.CMsg_21001003(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.center.CRegister.CMsg_21001003 other) {
        if (other == com.yaowan.protobuf.center.CRegister.CMsg_21001003.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 server_id = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.center.CMsg_21001003)
    }
    
    static {
      defaultInstance = new CMsg_21001003(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.center.CMsg_21001003)
  }
  
  public interface CMsg_22001003OrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class CMsg_22001003 extends
      com.google.protobuf.GeneratedMessageLite
      implements CMsg_22001003OrBuilder {
    // Use CMsg_22001003.newBuilder() to construct.
    private CMsg_22001003(Builder builder) {
      super(builder);
    }
    private CMsg_22001003(boolean noInit) {}
    
    private static final CMsg_22001003 defaultInstance;
    public static CMsg_22001003 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CMsg_22001003 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yaowan.protobuf.center.CRegister.CMsg_22001003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yaowan.protobuf.center.CRegister.CMsg_22001003 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yaowan.protobuf.center.CRegister.CMsg_22001003, Builder>
        implements com.yaowan.protobuf.center.CRegister.CMsg_22001003OrBuilder {
      // Construct using com.yaowan.protobuf.center.CRegister.CMsg_22001003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001003 getDefaultInstanceForType() {
        return com.yaowan.protobuf.center.CRegister.CMsg_22001003.getDefaultInstance();
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001003 build() {
        com.yaowan.protobuf.center.CRegister.CMsg_22001003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yaowan.protobuf.center.CRegister.CMsg_22001003 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yaowan.protobuf.center.CRegister.CMsg_22001003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yaowan.protobuf.center.CRegister.CMsg_22001003 buildPartial() {
        com.yaowan.protobuf.center.CRegister.CMsg_22001003 result = new com.yaowan.protobuf.center.CRegister.CMsg_22001003(this);
        return result;
      }
      
      public Builder mergeFrom(com.yaowan.protobuf.center.CRegister.CMsg_22001003 other) {
        if (other == com.yaowan.protobuf.center.CRegister.CMsg_22001003.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.yaowan.protobuf.center.CMsg_22001003)
    }
    
    static {
      defaultInstance = new CMsg_22001003(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yaowan.protobuf.center.CMsg_22001003)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
