// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMD.proto

package com.yaowan.protobuf.cmd;

public final class CMD {
  private CMD() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum CrossCMD
      implements com.google.protobuf.Internal.EnumLite {
    Test(0, 1),
    ;
    
    public static final int Test_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static CrossCMD valueOf(int value) {
      switch (value) {
        case 1: return Test;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CrossCMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CrossCMD>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CrossCMD>() {
            public CrossCMD findValueByNumber(int number) {
              return CrossCMD.valueOf(number);
            }
          };
    
    private final int value;
    
    private CrossCMD(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.yaowan.protobuf.cmd.CrossCMD)
  }
  
  public enum CenterCMD
      implements com.google.protobuf.Internal.EnumLite {
    ServerListAction(0, 1),
    ;
    
    public static final int ServerListAction_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static CenterCMD valueOf(int value) {
      switch (value) {
        case 1: return ServerListAction;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CenterCMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CenterCMD>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CenterCMD>() {
            public CenterCMD findValueByNumber(int number) {
              return CenterCMD.valueOf(number);
            }
          };
    
    private final int value;
    
    private CenterCMD(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.yaowan.protobuf.cmd.CenterCMD)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
